// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6oUu_2bj8WEeE01tfdlF7oM48KyVYwes',
    appId: '1:1040858109422:web:bda59bdc00640c9f20aaff',
    messagingSenderId: '1040858109422',
    projectId: 'expense-tracker-mobile-85d7a',
    authDomain: 'expense-tracker-mobile-85d7a.firebaseapp.com',
    storageBucket: 'expense-tracker-mobile-85d7a.firebasestorage.app',
    measurementId: 'G-9YS1KC8EBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ9pasHcVwbs1SJJET_M62wv1y6ZOWkuM',
    appId: '1:1040858109422:android:0978ee46271c58ef20aaff',
    messagingSenderId: '1040858109422',
    projectId: 'expense-tracker-mobile-85d7a',
    storageBucket: 'expense-tracker-mobile-85d7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpDOwHmcdQpSuJPhuKJWi0Fc9a697Bxrs',
    appId: '1:1040858109422:ios:15414585388c541620aaff',
    messagingSenderId: '1040858109422',
    projectId: 'expense-tracker-mobile-85d7a',
    storageBucket: 'expense-tracker-mobile-85d7a.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
